const CONFIG = {
  APP: {
    NAME: 'F-TIC-12 · Reporte de Incidencias y Fallas Tecnicas',
    CODIGO_FORMATO: 'F-TIC-12',
    VERSION_FORMATO: '01',
    VERSION_APP: '1.4.0',
    TIMEZONE: 'America/Lima',
    ENV: 'production',
    SUPPORT_EMAIL: 'soportetic@goydelperu.com'
  },

  VALIDATION: {
    DNI_LENGTH: 8,
    MOVIL_LENGTH: 9
  },

  TRACKING: {
    POLLING_MS: 15000,
    TERMINAL_STATUSES: ['Resuelto']
  },

  SPREADSHEETS: {
    MAIN: '1oruTWcOGtNptt9AmlSZDgaOROFdG8fhrQxk13SuA554',
    PADRON_PERSONAL: '123J9FsE1yJNK-YYRkwI94a9ZwurjV2Rmpyxo2xnDmqc'
  },

  DRIVE: {
    // Reserved for the future PDF + Drive phase.
    FOLDER_REGISTROS_UNITARIZADOS: '17ERnBJx2WaptCMg09jPKFF-HER9XFw1K',
    FOLDER_RG_F_TIC_12: '1OKA6cL1otH5v68CNOg1ivQyEa4otxyjR'
  },

  FORMATOS: {
    F_TIC_12_TEMPLATE_SPREADSHEET: '1jQGHmNFImUm81o8ICetauSrWVeVQdmWVGf2gmGbMMyo',
    F_TIC_12_TEMPLATE_SHEET: 'F-TIC-12'
  },

  PADRON: {
    SHEETS_EMPRESAS: {
      TDEM: 'TDEMSRL',
      GOYDEL: 'GOYDELSAC'
    },
    SHEET_PERSONAL_CENTRAL: 'PERSONAL_CENTRAL',
    EMPRESAS_CECO_ALIASES: {
      TDEM: ['TDEM', 'TDEM SRL', 'TDEMSRL'],
      GOYDEL: ['GOYDEL', 'GOYDEL SAC', 'GOYDELSAC'],
      METRIN: ['METRIN', 'METRIN SAC', 'METRINSAC']
    },
    SHEET_CECO: 'CECO',
    HEADERS_PERSONAL: {
      DNI: 'DNI',
      NOMBRE: 'APELLIDOS Y NOMBRES',
      CARGO: 'CARGO',
      PROYECTO: 'PROYECTO'
    },
    HEADERS_PERSONAL_CENTRAL: {
      RAZON_SOCIAL: 'RAZON_SOCIAL',
      DNI: 'DNI',
      NOMBRE: 'APELLIDOS_NOMBRES',
      CARGO: 'CARGO',
      MOVIL: 'MOVIL',
      CECO_NUMERO: 'CECO_NUMERO',
      CECO_NOMBRE: 'CECO_NOMBRE',
      AREA_PROYECTO: 'AREA_PROYECTO'
    },
    HEADERS_CECO: {
      RAZON_SOCIAL: 'RAZON SOCIAL',
      CECO: 'CECO',
      CENTRO_COSTO: 'CENTRO DE COSTO',
      PROYECTO: 'PROYECTO',
      ESTADO: 'ESTADO'
    }
  },

  SHEETS: {
    REGISTROS: 'MC-F-TIC-12',
    DICCIONARIO: 'DICC-F-TIC-12',
    TAGS: 'TAGS-F-TIC-12',
    LOG_EVENTOS: 'LOG_EVENTOS',
    LOG_ERRORES: 'LOG_ERRORES'
  },

  HEADERS: {
    REGISTROS: [
      'ID_REGISTRO', 'FECHA_HORA_REPORTE', 'FECHA_HORA_CIERRE', 'ESTADO_REGISTRO',
      'PERIODO_MES', 'PERIODO_AÑO', 'EMPRESA_DEL_GRUPO', 'NOMBRE_COMPLETO_SOLICITANTE',
      'DNI_SOLICITANTE', 'CARGO_SOLICITANTE', 'MOVIL_SOLICITANTE', 'PROYECTO_SEDE',
      'CENTRO_DE_COSTO', 'TIPO_EQUIPO', 'ACTIVO_AFECTADO', 'TIPO_PROBLEMA',
      'PRIORIDAD_USUARIO', 'DESCRIPCION_INCIDENCIA', 'ANYDESK_ID', 'ANYDESK_PASSWORD',
      'SLA_APLICADO', 'DIAGNOSTICO_TIC', 'ACCION_TOMADA', 'ESTADO_FINAL',
      'TECNICO_RESPONSABLE', 'CLASIFICACION_SEGURIDAD', 'CRITICIDAD_SEGURIDAD',
      'MTTR_HORAS', 'CUMPLIO_SLA', 'APORTA_I_O_27', 'APORTA_I_O_45',
      'LINK_PDF_REPORTE', 'HASH_SHA256_PDF', 'LINK_BITACORA_F_TIC_10',
      'LINK_INVENTARIO_F_TIC_05', 'URL_EVIDENCIA_ADICIONAL', 'DIAS_DESDE_REPORTE',
      'FLAG_DENTRO_SLA'
    ],
    LOG_EVENTOS: ['FECHA_HORA', 'USUARIO_EJECUCION', 'ACCION', 'ID_REGISTRO', 'RESULTADO', 'MENSAJE', 'EXTRA_JSON'],
    LOG_ERRORES: ['FECHA_HORA', 'USUARIO_EJECUCION', 'ACCION', 'ERROR', 'ERROR_STACK', 'EXTRA_JSON']
  },

  UI: {
    LOGO_PRINCIPAL_URL: '',
    COLOR_PRIMARIO: '#004a99',
    COLOR_SECUNDARIO: '#16a34a',
    COLOR_EXITO: '#16a34a',
    COLOR_ERROR: '#dc3545',
    COLOR_ALERTA: '#d97706',
    COLOR_TEXTO: '#1c2b4a',
    COLOR_MUTED: '#55606e'
  },

  SEGURIDAD: {
    // Script Property name that stores the AnyDesk encryption secret.
    ANYDESK_CIPHER_PROPERTY: 'ANYDESK_CIPHER_SECRET',
    ADMIN_ACCESS_CODE_PROPERTY: 'ADMIN_ACCESS_CODE'
  }
};

(function () {
  const headers = CONFIG.HEADERS.REGISTROS;
  for (let i = 0; i < headers.length; i++) {
    if (String(headers[i]).indexOf('PERIODO_A') === 0) {
      headers[i] = 'PERIODO_A\u00d1O';
    }
  }
})();
